title: Cloudevolve Blogs
description: Cloud, AWS, Azure & Cost Optimization
theme: minima
author: Cloudevolve

url: "https://cloudevolve-24.github.io"
baseurl: "/Clouevolve-blogs"

plugins:
  - jekyll-feed
