title: "Cloudevolve Blogs"
description: "Cloud cost optimization, FinOps & engineering playbooks from Cloudevolve."
theme: minima

# If hosting at https://cloudevolve.com/blogs
url: "https://cloudevolve.com"
baseurl: "/blogs"

# Nice-to-have
show_excerpts: true
permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed
